### ISSUE TITLE
Remove clojure-contrib dependency

### ISSUE THREAD

**Issue by tobias** [immutant/overlay#4]
We can probably move to data.xml - all we use contrilb for is to emit xml with an indent.

**Comment by jcrossley3** [comment]
Why is this an issue? data.xml ain't there yet.

**Comment by tobias** [comment]
Contrib is big and old, and no longer recommended. And what do you mean by "ain't there yet"? It can do exactly what we need - emit xml with indentation. It's just a different API.

**Comment by jcrossley3** [comment]
I don't think so, Tim.

**Comment by jcrossley3** [comment]
By the way, I'm big and old, and rarely recommended. Just sayin'.
